targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
          - lines_longer_than_80_chars
          # Only for the JSON literal output file
          - text_direction_code_point_in_literal

      builtvalue_jsonserializable:
        enabled: true

builders:
  builtvalue_jsonserializable:
    target: ":builtvalue_jsonserializable"
    import: "package:builtvalue_jsonserializable/builder.dart"
    builder_factories: ["builtValueJsonSerializableBuilder"]
    build_extensions: {".dart": ["bvjs.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

