name: builtvalue_jsonserializable
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  build: ^2.0.0
  built_collection: ^5.1.1
  built_value: ^8.4.1
  json_annotation: ^4.6.0
  source_gen: ^1.2.2

dev_dependencies:
  build_runner: ^2.2.0
  build_web_compilers: ^3.0.0
  built_value_generator: ^8.4.1
  json_serializable: ^6.3.0
  lints: ^2.0.0
  test: ^1.16.0
